Guns:
  Sniper:
    name: "Sniper Rifle"
    item: "DIAMOND_HOE"
    bullet-damage: 14
    bullet-velocity: 4.1
    bullet-amount: 1
    shooting-cooldown: 1250
    shooting-sound: "ENTITY_FIREWORK_ROCKET_BLAST"
    shooting-sound-pitch: 1.0
    shooting-sound-volume: 1.0
    scatter-area: 0.1
    penalty-base: 1.0
    sprint-base: 1.0
    jump-base: 1.0
  SMG:
    name: "Sub Machine Gun"
    item: "IRON_HOE"
    bullet-damage: 2.5
    bullet-velocity: 3
    bullet-amount: 1
    shooting-cooldown: 160
    shooting-sound: "BLOCK_STONE_BUTTON_CLICK_ON"
    shooting-sound-pitch: 1.0
    shooting-sound-volume: 1.0
    scatter-area: 2.0
    penalty-base: 1.0
    sprint-base: 1.0
    jump-base: 1.0
  Shotgun:
    name: "Shotgun"
    item: "GOLDEN_HOE"
    bullet-damage: 3.2
    bullet-velocity: 0.95
    bullet-amount: 8
    shooting-cooldown: 1000
    shooting-sound: "BLOCK_PISTON_CONTRACT"
    shooting-sound-pitch: 1.0
    shooting-sound-volume: 1.0
    scatter-area: 7.0
    penalty-base: 1.0
    sprint-base: 0.5
    jump-base: 0.5
  Pistol:
    name: "Pistol"
    item: "NETHERITE_HOE"
    bullet-damage: 2.5
    bullet-velocity: 2.5
    bullet-amount: 1
    shooting-cooldown: 240
    shooting-sound: "ITEM_DYE_USE"
    shooting-sound-pitch: 1.0
    shooting-sound-volume: 1.0
    scatter-area: 1.0
    penalty-base: 1.0
    sprint-base: 1.0
    jump-base: 1.0